Repository kowainik/typerep-map, pull requests merged in 2018-07, with the labels that each got.

#9 [#5] Rename OptimalVector to Map
  .travis.yml
  benchmark/Map.hs
  benchmark/OptimalVector.hs
  src/Data/TypeRep/CMap.hs
  src/Data/TypeRep/Map.hs
  src/Data/TypeRep/OptimalVector.hs
  test/Test/TypeRep/Map.hs
  test/Test/TypeRep/VectorOpt.hs
  typerep-map.cabal
Labels: refactoring

#10 [#4] Move CMap and Vector to the internal library
  Setup.hs
  benchmark/Map.hs
  src/Data/TypeRep/CMap.hs
  src/Data/TypeRep/Map.hs
  src/Data/TypeRep/Vector.hs
  typerep-map.cabal
Labels: refactoring, structure

#13 [#7] Implement insert for CachedMap
  internal/Data/TypeRep/CacheMap.hs
  test/Test/TypeRep/CacheMap.hs
  typerep-map.cabal
Labels: enhancement

#14 Add benchmarks with DMap
  benchmark/CacheMap.hs
  benchmark/DMap.hs
  benchmark/Main.hs
  typerep-map.cabal
Labels: bench

#16 [#8] Add property tests for insert lookup
  .travis.yml
  internal/Data/TypeRep/CacheMap.hs
  test/Test/TypeRep/MapProperty.hs
  typerep-map.cabal
Labels: bug, enhancement, tests

#18 [#6] Add README, refresh docs, refactor, add hlint
  .hlint.yaml
  README.md
  benchmark/CacheMap.hs
  benchmark/OptimalVector.hs
  benchmark/Vector.hs
  internal/Data/TypeRep/CacheMap.hs
  internal/Data/TypeRep/OptimalVector.hs
  internal/Data/TypeRep/Vector.hs
  src/Data/TypeRep/Map.hs
  test/Test/TypeRep/CacheMap.hs
  test/Test/TypeRep/Vector.hs
  test/Test/TypeRep/VectorOpt.hs
Labels: docs, refactoring

#19 [#17] Add more map-like functions
  README.md
  internal/Data/TypeRep/CacheMap.hs
  src/Data/TypeRep/Map.hs
  test/Test/TypeRep/MapProperty.hs
  typerep-map.cabal
Labels: enhancement

#23 [#21] Unpack fields
  internal/Data/TypeRep/CacheMap.hs
Labels: enhancement

#26 [#22] Add 'hoist'
  internal/Data/TypeRep/CacheMap.hs
  src/Data/TypeRep/Map.hs
Labels: enhancement

#28 [#20] Use PrimArray instead of Vector
  benchmark/CacheMap.hs
  benchmark/Main.hs
  internal/Data/TypeRep/CacheMap.hs
  stack.yaml
  typerep-map.cabal
Labels: enhancement

#29 [#24] Add union and unionWith
  internal/Data/TypeRep/CacheMap.hs
  src/Data/TypeRep/Map.hs
  test/Test/TypeRep/CacheMap.hs
Labels: enhancement

#32 [#25] Add TMap, restructure internal lib
  benchmark/CacheMap.hs
  internal/Data/TypeRep/CacheMap.hs
  src/Data/TypeRep/Map.hs
  src/Data/TypeRep/TMap.hs
  test/Test/TypeRep/CacheMap.hs
  test/Test/TypeRep/MapProperty.hs
  typerep-extra-impls/Data/TypeRep/CMap.hs
  typerep-extra-impls/Data/TypeRep/OptimalVector.hs
  typerep-extra-impls/Data/TypeRep/Vector.hs
  typerep-map.cabal
Labels: enhancement, refactoring, structure

#34 [#31] Add Semigroup and Monoid instances
  .travis.yml
  CHANGELOG.md
  src/Data/TypeRep/Map.hs
  test/Test/TypeRep/MapProperty.hs
  typerep-map.cabal
Labels: enhancement, refactoring, tests

#35 [#27] Add table with benchmark results to README
  README.md
Labels: bench, docs

#36 Add 'shell.nix'
  shell.nix
Labels: enhancement

#38 Update documentation and module structure
  README.md
  benchmark/CacheMap.hs
  src/Data/TMap.hs
  src/Data/TypeRep/TMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
  test/Test/TypeRep/CacheMap.hs
  test/Test/TypeRep/MapProperty.hs
  typerep-map.cabal
Labels: docs, refactoring

#41 Fix the DMap benchmark
  benchmark/DMap.hs
Labels: bench, bug

#44 [#43] IsList instance
  .travis.yml
  CHANGELOG.md
  benchmark/CacheMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
  test/Test/TypeRep/CacheMap.hs
  test/Test/TypeRep/MapProperty.hs
  typerep-map.cabal
Labels: enhancement, refactoring

#45 [#39] Add hoistWithKey and map for TMap
  CHANGELOG.md
  src/Data/TMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
Labels: enhancement
