Repository kowainik/typerep-map, pull requests merged in 2020-10, with the labels that each got.

#93 Remove dependency on containers
  src/Data/TypeRepMap/Internal.hs
  test/Test/TypeRep/TypeRepMapProperty.hs
  typerep-map.cabal
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, refactoring

#94 Improve delete & insert performance
  src/Data/TMap.hs
  src/Data/TypeRepMap/Internal.hs
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#100 Use deleteFirst instead of filter
  src/Data/TypeRepMap/Internal.hs
Labels: enhancement

#101 further improvement on insert
  src/Data/TypeRepMap/Internal.hs
Labels: hacktoberfest-accepted, performance :horse:

#95 Add "alter" combinator
  src/Data/TMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
  test/Test/TypeRep/TypeRepMapProperty.hs
Labels: Hacktoberfest, hacktoberfest-accepted

#96 Add intersection/intersectionWith
  src/Data/TMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
  test/Test/TypeRep/TypeRepMapProperty.hs
Labels: Hacktoberfest, hacktoberfest-accepted
