Repository kowainik/typerep-map, pull requests merged in 2020-04, with the labels that each got.

#84 [#83] Support GHC-8.10
  .github/workflows/ci.yml
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE
  shell.nix
  src/Data/TMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
  stack.yaml
  typerep-extra-impls/Data/TypeRep/CMap.hs
  typerep-extra-impls/Data/TypeRep/OptimalVector.hs
  typerep-extra-impls/Data/TypeRep/Vector.hs
  typerep-map.cabal
Labels: CI

#88 [#87] Move tests to hspec
  stack.yaml
  test/Test.hs
  test/Test/TypeRep/CMap.hs
  test/Test/TypeRep/TypeRepMap.hs
  test/Test/TypeRep/TypeRepMapProperty.hs
  test/Test/TypeRep/Vector.hs
  test/Test/TypeRep/VectorOpt.hs
  typerep-map.cabal
Labels: library, tests

#85 Update benchmarks for newer GHC versions
  README.md
  typerep-map.cabal
Labels: bench

#86 Build on Windows CI, update badges
  README.md
  appveyor.yml
Labels: CI

#89 Build only with stack on Travis CI
  .travis.yml
Labels: CI

#91 [#90] Check more ghc warnings through ghc-options
  benchmark/CMap.hs
  benchmark/CacheMap.hs
  benchmark/DMap.hs
  benchmark/Main.hs
  benchmark/OptimalVector.hs
  benchmark/Spec.hs
  benchmark/Vector.hs
  src/Data/TMap.hs
  src/Data/TypeRepMap/Internal.hs
  test/Test/TypeRep/TypeRepMapProperty.hs
  typerep-extra-impls/Data/TypeRep/CMap.hs
  typerep-extra-impls/Data/TypeRep/OptimalVector.hs
  typerep-extra-impls/Data/TypeRep/Vector.hs
  typerep-map.cabal
Labels: enhancement, refactoring
