Repository kowainik/typerep-map, pull requests merged in 2021-08, with the labels that each got.

#108 Bumped dependencies to support GHC 9
  typerep-map.cabal
Labels: library

#110 [#109] Support GHC-9.0
  .github/workflows/ci.yml
  .travis.yml
  CHANGELOG.md
  README.md
  appveyor.yml
  benchmark/CMap.hs
  benchmark/CacheMap.hs
  benchmark/DMap.hs
  src/Data/TMap.hs
  src/Data/TypeRepMap/Internal.hs
  stack.yaml
  typerep-map.cabal
Labels: CI, library

#111 Prepare 0.4.0.0 release
  .github/workflows/ci.yml
  .headroom.yaml
  CHANGELOG.md
  src/Data/TMap.hs
  src/Data/TypeRepMap.hs
  src/Data/TypeRepMap/Internal.hs
  typerep-map.cabal
Labels: docs
